<?xml version="1.0" encoding="UTF-8"?>

<testsuites tests="1" failures="1" errors="1" assertions="0" skipped="0">
  <testsuite name="default">
    <properties><property name="Lua Version" value="Lua 5.4" /></properties>
    <testcase name="jabberwock" classname="default" assertions="0">
      <error message="tests/junit-output.lua:67: I did a boo-boo">
        <![CDATA[stack traceback:
	loon/snap.lua:99: in upvalue 'yourAssert'
	loon/init.lua:545: in function 'loon.snap.output'
	tests/junit-output.lua:65: in function <tests/junit-output.lua:32>
	[C]: in function 'xpcall'
	loon/init.lua:179: in function <loon/init.lua:160>
	(...tail calls...)
	loon/init.lua:591: in function 'loon.run'
	tests/[[path normalized for test]]
	[C]: in ?]]>
      </error>
    </testcase>
  </testsuite>
</testsuites>
